name: guess_the_number
description: "Solvatech test task"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  hydrated_bloc: ^9.1.5
  path_provider: ^2.1.5
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  equatable: ^2.0.7
  rxdart: ^0.28.0
  formz: ^0.8.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-VariableFont.ttf
